-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1:3308
-- Tiempo de generación: 15-04-2020 a las 01:45:37
-- Versión del servidor: 8.0.18
-- Versión de PHP: 7.3.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `contenido`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `articulos`
--

DROP TABLE IF EXISTS `articulos`;
CREATE TABLE IF NOT EXISTS `articulos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Titulo` varchar(200) NOT NULL,
  `Descripcion` text NOT NULL,
  `Autor` varchar(70) NOT NULL,
  `Fecha` datetime NOT NULL,
  `Aprobado` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Volcado de datos para la tabla `articulos`
--

INSERT INTO `articulos` (`id`, `Titulo`, `Descripcion`, `Autor`, `Fecha`, `Aprobado`) VALUES
(1, '¿Qué hace este plugin?', '<p>Una pr&aacute;ctica habitual en la creaci&oacute;n de bases de datos es establecer&nbsp;<strong>claves primarias</strong>&nbsp;(o&nbsp;<em>Primary Keys</em>, PKs) con la opci&oacute;n de&nbsp;<strong>auto incremento</strong>. De esta manera, no hay que preocuparse por especificar un valor num&eacute;rico &uacute;nico de clave primaria cada vez que se inserte una nueva fila en la tabla.</p>\r\n\r\n<p>Pese a que&nbsp;<strong>phpMyAdmin</strong>&nbsp;es una herramienta de gesti&oacute;n de bases de datos muy &uacute;til y f&aacute;cil de usar, muchas verces oigo la pregunta de&nbsp;<em>d&oacute;nde especificar el auto incremento en phpMyAdmin</em>. He aqu&iacute; la soluci&oacute;n:</p>\r\n', 'Maria2021', '2020-04-06 15:34:07', 1),
(2, 'Fatal error: Call to a member function prepare()', '<p>Para comprobar que la propiedad de auto incremento se configur&oacute; correctamente, no hay m&aacute;s que mirar en la columna&nbsp;<strong>EXTRA</strong>&nbsp;dentro de las propiedades de la columna de la clave primaria de la tabla (tras haber seleccionado la tabla, y dentro de la secci&oacute;n de estructura,&nbsp;<em>Structure</em>). Si en&nbsp;<em>extra</em>&nbsp;aparece el texto&nbsp;<em>auto_increment</em>, la configuraci&oacute;n del incremento autom&aacute;tico fue exitosa.</p>\r\n\r\n<p>Sin embargo, en versiones m&aacute;s antiguas de phpMyAdmin, el auto incremento se configuraba de forma diferente, editando directamente estas propiedades extra de la columna. La opci&oacute;n de&nbsp;<strong>auto_increment</strong>&nbsp;se encontraba dentro de un men&uacute; desplegable en la categor&iacute;a&nbsp;<strong>EXTRA</strong>&nbsp;(la &uacute;ltima columna en el men&uacute; de creaci&oacute;n de campos).</p>\r\n\r\n<p><iframe allowfullscreen=\"\" frameborder=\"0\" height=\"360\" src=\"https://www.youtube.com/embed/JZ_3WRN0Owg?start=2\" width=\"640\"></iframe></p>\r\n', 'TatyM19', '2020-04-06 15:37:27', 0),
(4, 'Start building', '<p>Si necesita asegurarse de que el campo que se est&aacute; auto-incrementando es de hecho la&nbsp;<strong>clave primaria</strong>&nbsp;de la tabla actual, se puede volver a asignar la clave primaria de la tabla pulsando en el&nbsp;<strong>icono de llave</strong>&nbsp;correspondiente a la fila del campo deseado.</p>\r\n\r\n<p>Hay que tener en cuenta que s&oacute;lo puede especificarse&nbsp;<strong>un campo con auto incremento</strong>&nbsp;por cada tabla en MySQL. Por otra parte, el incremento autom&aacute;tico s&oacute;lo tiene sentido con claves primarias num&eacute;ricas, y s&oacute;lo puede haber una clave primaria en cada tabla MySQL.</p>\r\n\r\n<p>Por &uacute;ltimo, si lo que desea es cambiar el&nbsp;<strong>valor del auto incremento</strong>&nbsp;en phpMyAdmin (por ejemplo, para que el campo de auto incremento comience en un n&uacute;mero concreto), s&oacute;lo hay que seleccionar la solapa&nbsp;<strong>Operations</strong>&nbsp;(operaciones) en phpMyAdmin, y escribir en el campo llamado&nbsp;<strong>AUTO_INCREMENT</strong>&nbsp;el&nbsp;<em>nuevo valor inicial</em>&nbsp;del campo con auto incremento y guardar los cambios.</p>\r\n\r\n<p><img alt=\"\" src=\"ckeditor/uploads/imagen256.jpg\" style=\"height:256px; width:256px\" /></p>\r\n', 'AngelaC800', '2020-04-06 15:49:27', 0),
(5, 'Learn new skills', '<p>We&rsquo;re making tools and resources available so that anyone can use technology to solve problems. Whether you&rsquo;re just getting started or you&rsquo;re already an expert, you&rsquo;ll find the resources you need to reach your next breakthrough. We&rsquo;re fostering a growing ecosystem of AI-powered businesses and applications with mentorship, education, and resources to help everyone innovate and thrive.</p>\r\n\r\n<p>We believe in fostering a rich and collaborative environment for researchers and developers. That&#39;s why we share large-scale datasets that anyone can use to further their work.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><img alt=\"\" src=\"ckeditor/uploads/luna2.jpg\" style=\"float:left; height:256px; width:256px\" /></p>\r\n', 'Hanna6000', '2020-04-06 15:59:57', 0),
(6, 'Ce soir, on regarde quoi ?', '<p>Vous &ecirc;tes un peu&nbsp;d&eacute;prim&eacute; en ces temps de confinement&nbsp;? Apr&egrave;s avoir vu ou revu ces &laquo;&nbsp;feel-good movies&nbsp;&raquo;, &ccedil;a ira forc&eacute;ment mieux. Promis.&nbsp;Et il y en a pour tous les go&ucirc;ts ;)</p>\r\n\r\n<p>Je n&#39;ai pas d&#39;enfant, mais j&#39;ai trouv&eacute; le chat avec Isabelle Filliozat vachement bien. Apr&egrave;s l&#39;avoir lu, j&#39;&eacute;tais plus d&eacute;tendue (alors que je n&#39;avais m&ecirc;me pas la sensation d&#39;&ecirc;tre tendue avant). Pas mal de bons conseils &agrave; s&#39;appliquer &agrave; soi finalement, enfant ou pas :)<br />\r\n<br />\r\n<strong>-Lilou</strong></p>\r\n\r\n<p><strong><img alt=\"\" src=\"ckeditor/uploads/imagenoscura.jpg\" style=\"float:left; height:170px; width:255px\" /></strong></p>\r\n', 'Melly2000', '2020-04-06 16:03:11', 0),
(8, 'La Navidad ', '<p>La Navidad&nbsp;<strong>es una festividad religiosa en la que los cristianos conmemoran el nacimiento de Jesucristo</strong>. Se celebra el 25 de diciembre de cada a&ntilde;o. De hecho, la palabra Navidad, como tal, procede del lat&iacute;n&nbsp;<em>nativĭtas</em>,&nbsp;<em>nativātis&nbsp;</em>que significa &lsquo;nacimiento&rsquo;.</p>\r\n\r\n<p>Este t&eacute;rmino, sin embargo, se utiliza no solo para referirse al d&iacute;a en que se celebra el nacimiento de Jes&uacute;s (la Nochebuena), sino que tambi&eacute;n se extiende para designar el periodo posterior, hasta el D&iacute;a de Reyes.</p>\r\n\r\n<p>Actualmente, la Navidad se celebra en muchos lugares y de formas muy distintas. En general, una de las caracter&iacute;sticas actuales de la Navidad es el aumento del consumo, en especial de objetos utilizados como regalos y alimentos.</p>\r\n\r\n<p>Desde el punto de vista cristiano, no obstante, se considera que este no es el significado aut&eacute;ntico de la Navidad. El significado de la Navidad, muy por el contrario, responde a manifestaci&oacute;n de ciertos valores humanos que durante el a&ntilde;o se mantienen m&aacute;s o menos en el olvido.</p>\r\n\r\n<p>Valores como la solidaridad, la uni&oacute;n, el amor, la paz y la esperanza son m&aacute;s propios de la &eacute;poca de Navidad, y se encuentran representados en las creencias religiosas del cristianis</p>\r\n\r\n<p><iframe allowfullscreen=\"\" frameborder=\"0\" height=\"360\" src=\"https://www.youtube.com/embed/SQlIiCD-wr8\" width=\"640\"></iframe></p>\r\n', 'Andres70', '2020-04-06 23:48:00', 0),
(9, 'La Navidad ', '<p>La Navidad&nbsp;<strong>es una festividad religiosa en la que los cristianos conmemoran el nacimiento de Jesucristo</strong>. Se celebra el 25 de diciembre de cada a&ntilde;o. De hecho, la palabra Navidad, como tal, procede del lat&iacute;n&nbsp;<em>nativĭtas</em>,&nbsp;<em>nativātis&nbsp;</em>que significa &lsquo;nacimiento&rsquo;.</p>\r\n\r\n<p>Este t&eacute;rmino, sin embargo, se utiliza no solo para referirse al d&iacute;a en que se celebra el nacimiento de Jes&uacute;s (la Nochebuena), sino que tambi&eacute;n se extiende para designar el periodo posterior, hasta el D&iacute;a de Reyes.</p>\r\n\r\n<p>Actualmente, la Navidad se celebra en muchos lugares y de formas muy distintas. En general, una de las caracter&iacute;sticas actuales de la Navidad es el aumento del consumo, en especial de objetos utilizados como regalos y alimentos.</p>\r\n\r\n<p>Desde el punto de vista cristiano, no obstante, se considera que este no es el significado aut&eacute;ntico de la Navidad. El significado de la Navidad, muy por el contrario, responde a manifestaci&oacute;n de ciertos valores humanos que durante el a&ntilde;o se mantienen m&aacute;s o menos en el olvido.</p>\r\n\r\n<p>Valores como la solidaridad, la uni&oacute;n, el amor, la paz y la esperanza son m&aacute;s propios de la &eacute;poca de Navidad, y se encuentran representados en las creencias religiosas del cristianis</p>\r\n\r\n<p><iframe allowfullscreen=\"\" frameborder=\"0\" height=\"360\" src=\"https://www.youtube.com/embed/SQlIiCD-wr8\" width=\"640\"></iframe></p>\r\n', 'Andres70', '2020-04-06 23:54:43', 0),
(10, 'Start building', '<p>La Navidad fue establecida en el d&iacute;a 25 de diciembre como d&iacute;a de solemnidad por la Iglesia cat&oacute;lica en el a&ntilde;o 350 gracias al papa Julio.</p>\r\n\r\n<p>En la Biblia, sin embargo, no es mencionado el d&iacute;a exacto del nacimiento de Jes&uacute;s. De all&iacute; que la celebraci&oacute;n de la Navidad en principio no formara parte de las tradiciones cristianas.</p>\r\n\r\n<p>La raz&oacute;n de fijar el d&iacute;a 25 de diciembre como fecha de festejo del nacimiento de Jesucristo responde a la necesidad de la Iglesia de sustituir la fiesta de las Saturnales (o Saturnalia), tradicional en la Antigua Roma, que coincid&iacute;a con el solsticio de invierno y que era celebrada por los llamados paganos, y as&iacute; facilitar la aceptaci&oacute;n del cristianismo.</p>\r\n\r\n<p><img alt=\"\" src=\"ckeditor/uploads/imagen256.jpg\" style=\"height:256px; width:256px\" /></p>\r\n', 'AngelaC800', '2020-04-07 00:04:12', 0),
(11, 'Origen ', '<h2>Origen&nbsp;<img alt=\"\" src=\"ckeditor/uploads/imagen256.jpg\" style=\"height:256px; width:256px\" /></h2>\r\n', 'AngelaC800', '2020-04-07 00:05:33', 0),
(21, 'Bosque 2', '<p>Bosque2.<img alt=\"\" src=\"ckeditor/uploads/1_Nature3.jpg\" style=\"height:678px; width:1024px\" />Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas feugiat consequat diam. Maecenas metus. Vivamus diam purus, cursus a, commodo non, facilisis vitae, nulla. Aenean dictum lacinia tortor. Nunc iaculis, nibh non iaculis aliquam, orci felis euismod neque, sed ornare massa mauris sed velit. Nulla pretium mi et risus. Fusce mi pede, tempor id, cursus ac, ullamcorper nec, enim. Sed tortor. Curabitur molestie. Duis velit augue, condimentum at, ultrices a, luctus ut, orci. Donec pellentesque egestas eros. Integer cursus, augue in cursus faucibus, eros pede bibendum sem, in tempus tellus justo quis ligula. Etiam eget tortor. Vestibulum rutrum, est ut placerat elementum, lectus nisl aliquam velit, tempor aliquam eros nunc nonummy metus. In eros metus, gravida a, gravida sed, lobortis id, turpis. Ut ultrices, ipsum at venenatis fringilla, sem nulla lacinia tellus, eget aliquet turpis mauris non enim. Nam turpis. Suspendisse lacinia. Curabitur ac tortor ut ipsum egestas elementum. Nunc imperdiet gravida mauris.</p>\r\n\r\n<p>◢</p>\r\n\r\n<p><a href=\"javascript:void(0)\" id=\"cke_144_uiElement\" title=\"Aceptar\">Aceptar</a><a href=\"javascript:void(0)\" id=\"cke_146_uiElement\" title=\"Cancelar\">Cancelar</a></p>\r\n', 'Andres70', '2020-04-14 15:19:01', 0),
(13, 'ArticuloPrueba1-Nada pueda malir sal', '<p><img alt=\"\" src=\"ckeditor/uploads/t6-figuras.png\" style=\"height:564px; width:383px\" /></p>\r\n\r\n<h3>The standard Lorem Ipsum passage, used since the 1500s</h3>\r\n\r\n<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n\r\n<h3>Section 1.10.32 of &quot;de Finibus Bonorum et Malorum&quot;, written by Cicero in 45 BC</h3>\r\n\r\n<p>&quot;Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?&quot;</p>\r\n\r\n<h3>1914 translation by H. Rackham</h3>\r\n\r\n<p>&quot;But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?&quot;</p>\r\n', 'new3', '2020-04-11 02:27:39', 0),
(14, 'ArticuloPrueba1-Nada pueda malir sal', '<p><img alt=\"\" src=\"ckeditor/uploads/t6-figuras.png\" style=\"height:564px; width:383px\" /></p>\r\n\r\n<h3>The standard Lorem Ipsum passage, used since the 1500s</h3>\r\n\r\n<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n\r\n<h3>Section 1.10.32 of &quot;de Finibus Bonorum et Malorum&quot;, written by Cicero in 45 BC</h3>\r\n\r\n<p>&quot;Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?&quot;</p>\r\n\r\n<h3>1914 translation by H. Rackham</h3>\r\n\r\n<p>&quot;But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?&quot;</p>\r\n', 'new3', '2020-04-11 02:29:49', 0),
(15, ' Mona Arte', '<p><a href=\"javascript:void(0)\" id=\"cke_158_previewLink\" onclick=\"return false;\" target=\"_blank\"><img alt=\"\" id=\"cke_159_previewImage\" src=\"http://localhost/WikiA/LoginPHP/ckeditor/uploads/I_diferente2.jpg\" /></a></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas feugiat consequat diam. Maecenas metus. Vivamus diam purus, cursus a, commodo non, facilisis vitae, nulla. Aenean dictum lacinia tortor. Nunc iaculis, nibh non iaculis aliquam, orci felis euismod neque, sed ornare massa mauris sed velit. Nulla pretium mi et risus. Fusce mi pede, tempor id, cursus ac, ullamcorper nec, enim. Sed tortor. Curabitur molestie. Duis velit augue, condimentum at, ultrices a, luctus ut, orci. Donec pellentesque egestas eros. Integer cursus, augue in cursus faucibus, eros pede bibendum sem, in tempus tellus justo quis ligula. Etiam eget tortor. Vestibulum rutrum, est ut placerat elementum, lectus nisl aliquam velit, tempor aliquam eros nunc nonummy metus. In eros metus, gravida a, gravida sed, lobortis id, turpis. Ut ultrices, ipsum at venenatis fringilla, sem nulla lacinia tellus, eget aliquet turpis mauris non enim. Nam turpis. Suspendisse lacinia. Curabitur ac tortor ut ipsum egestas elementum. Nunc imperdiet gravida mauris.</p>\r\n', 'new3', '2020-04-12 01:13:07', 0),
(16, ' Mona Arte', '<p><a href=\"javascript:void(0)\" id=\"cke_158_previewLink\" onclick=\"return false;\" target=\"_blank\"><img alt=\"\" id=\"cke_159_previewImage\" src=\"http://localhost/WikiA/LoginPHP/ckeditor/uploads/I_diferente2.jpg\" /></a></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas feugiat consequat diam. Maecenas metus. Vivamus diam purus, cursus a, commodo non, facilisis vitae, nulla. Aenean dictum lacinia tortor. Nunc iaculis, nibh non iaculis aliquam, orci felis euismod neque, sed ornare massa mauris sed velit. Nulla pretium mi et risus. Fusce mi pede, tempor id, cursus ac, ullamcorper nec, enim. Sed tortor. Curabitur molestie. Duis velit augue, condimentum at, ultrices a, luctus ut, orci. Donec pellentesque egestas eros. Integer cursus, augue in cursus faucibus, eros pede bibendum sem, in tempus tellus justo quis ligula. Etiam eget tortor. Vestibulum rutrum, est ut placerat elementum, lectus nisl aliquam velit, tempor aliquam eros nunc nonummy metus. In eros metus, gravida a, gravida sed, lobortis id, turpis. Ut ultrices, ipsum at venenatis fringilla, sem nulla lacinia tellus, eget aliquet turpis mauris non enim. Nam turpis. Suspendisse lacinia. Curabitur ac tortor ut ipsum egestas elementum. Nunc imperdiet gravida mauris.</p>\r\n', 'new3', '2020-04-12 03:14:58', 0),
(17, 'Big Ben', '<p>&nbsp;</p>\r\n\r\n<p><img alt=\"\" src=\"ckeditor/uploads/I_diferente3.jpg\" style=\"height:788px; width:557px\" />I</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas feugiat consequat diam. Maecenas metus. Vivamus diam purus, cursus a, commodo non, facilisis vitae, nulla. Aenean dictum lacinia tortor. Nunc iaculis, nibh non iaculis aliquam, orci felis euismod neque, sed ornare massa mauris sed velit. Nulla pretium mi et risus. Fusce mi pede, tempor id, cursus ac, ullamcorper nec, enim. Sed tortor. Curabitur molestie. Duis velit augue, condimentum at, ultrices a, luctus ut, orci. Donec pellentesque egestas eros. Integer cursus, augue in cursus faucibus, eros pede bibendum sem, in tempus tellus justo quis ligula. Etiam eget tortor. Vestibulum rutrum, est ut placerat elementum, lectus nisl aliquam velit, tempor aliquam eros nunc nonummy metus. In eros metus, gravida a, gravida sed, lobortis id, turpis. Ut ultrices, ipsum at venenatis fringilla, sem nulla lacinia tellus, eget aliquet turpis mauris non enim. Nam turpis. Suspendisse lacinia. Curabitur ac tortor ut ipsum egestas elementum. Nunc imperdiet gravida mauris.</p>\r\n\r\n<p>◢</p>\r\n\r\n<p><a href=\"javascript:void(0)\" id=\"cke_134_uiElement\" title=\"Aceptar\">Aceptar</a><a href=\"javascript:void(0)\" id=\"cke_136_uiElement\" title=\"Cancelar\">Cancelar</a></p>\r\n', 'new3', '2020-04-14 00:04:59', 0),
(18, 'Bosque embrujado', '<p>Bosque&nbsp;</p>\r\n\r\n<p><img alt=\"\" src=\"ckeditor/uploads/1_Nature3.jpg\" style=\"height:678px; width:1024px\" />Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas feugiat consequat diam. Maecenas metus. Vivamus diam purus, cursus a, commodo non, facilisis vitae, nulla. Aenean dictum lacinia tortor. Nunc iaculis, nibh non iaculis aliquam, orci felis euismod neque, sed ornare massa mauris sed velit. Nulla pretium mi et risus. Fusce mi pede, tempor id, cursus ac, ullamcorper nec, enim. Sed tortor. Curabitur molestie. Duis velit augue, condimentum at, ultrices a, luctus ut, orci. Donec pellentesque egestas eros. Integer cursus, augue in cursus faucibus, eros pede bibendum sem, in tempus tellus justo quis ligula. Etiam eget tortor. Vestibulum rutrum, est ut placerat elementum, lectus nisl aliquam velit, tempor aliquam eros nunc nonummy metus. In eros metus, gravida a, gravida sed, lobortis id, turpis. Ut ultrices, ipsum at venenatis fringilla, sem nulla lacinia tellus, eget aliquet turpis mauris non enim. Nam turpis. Suspendisse lacinia. Curabitur ac tortor ut ipsum egestas elementum. Nunc imperdiet gravida mauris.</p>\r\n\r\n<p>◢</p>\r\n', 'AngelaC800', '2020-04-14 14:35:40', 0);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
